--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6 (Homebrew)
-- Dumped by pg_dump version 16.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: card_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.card_entity (
    expiry_date date,
    is_closed boolean,
    is_paused boolean,
    is_pinned boolean,
    is_shared boolean,
    latitude double precision,
    longitude double precision,
    per_day double precision,
    per_month double precision,
    per_transaction double precision,
    per_week double precision,
    per_year double precision,
    radius double precision,
    remaining_limit double precision,
    spending_limit double precision,
    total double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    limit_set_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    bank_account_number character varying(255),
    card_color character varying(255),
    card_icon character varying(255),
    card_name character varying(255),
    card_number character varying(255),
    card_type character varying(255),
    category_name character varying(255),
    cvv character varying(255),
    merchant_name character varying(255)
);


ALTER TABLE public.card_entity OWNER TO postgres;

--
-- Name: card_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.card_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_entity (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chat_entity OWNER TO postgres;

--
-- Name: chat_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages_entity (
    chat_id bigint,
    id bigint NOT NULL,
    sender_id bigint,
    sent_at timestamp(6) without time zone,
    message_content character varying(255)
);


ALTER TABLE public.messages_entity OWNER TO postgres;

--
-- Name: messages_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification_entity (
    read boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    body text NOT NULL,
    title character varying(255) NOT NULL,
    data jsonb
);


ALTER TABLE public.notification_entity OWNER TO postgres;

--
-- Name: notification_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plan_entity (
    daily_spend_limit double precision NOT NULL,
    has_category_locking boolean NOT NULL,
    has_location_locking boolean NOT NULL,
    has_merchant_locking boolean NOT NULL,
    monthly_card_issuance_limit integer NOT NULL,
    monthly_spend_limit double precision NOT NULL,
    price double precision NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.plan_entity OWNER TO postgres;

--
-- Name: plan_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plan_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shared_card_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shared_card_entity (
    card_id bigint,
    expires_at timestamp(6) without time zone,
    id bigint NOT NULL,
    shared_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.shared_card_entity OWNER TO postgres;

--
-- Name: shared_card_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shared_card_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shared_card_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription_entity (
    amount double precision NOT NULL,
    is_active boolean NOT NULL,
    card_id bigint NOT NULL,
    id bigint NOT NULL,
    last_charge_date timestamp(6) without time zone NOT NULL,
    next_charge_date timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    billing_cycle character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    merchant character varying(255) NOT NULL
);


ALTER TABLE public.subscription_entity OWNER TO postgres;

--
-- Name: subscription_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction_entity (
    amount double precision NOT NULL,
    is_recurring boolean NOT NULL,
    latitude double precision,
    longitude double precision,
    card_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    category character varying(255) NOT NULL,
    decline_reason text,
    description text,
    merchant character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);


ALTER TABLE public.transaction_entity OWNER TO postgres;

--
-- Name: transaction_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_entity (
    auto_renewal boolean NOT NULL,
    current_daily_spend double precision NOT NULL,
    current_month_card_issuance integer NOT NULL,
    current_monthly_spend double precision NOT NULL,
    daily_spend_limit double precision NOT NULL,
    date_of_birth date,
    is_active boolean,
    monthly_card_issuance_limit integer NOT NULL,
    monthly_spend_limit double precision NOT NULL,
    notification_enabled boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_spend_reset timestamp(6) without time zone NOT NULL,
    plan_end_date timestamp(6) without time zone,
    plan_start_date timestamp(6) without time zone,
    bank_account_number character varying(255),
    bank_account_username character varying(255),
    civil_id character varying(255),
    department character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    gender character varying(255),
    last_name character varying(255),
    notification_token character varying(255),
    password character varying(255) NOT NULL,
    permission character varying(255),
    phone_number character varying(255) NOT NULL,
    plan character varying(255),
    profile_pic character varying(255),
    role character varying(255)
);


ALTER TABLE public.user_entity OWNER TO postgres;

--
-- Name: user_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: card_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.card_entity (expiry_date, is_closed, is_paused, is_pinned, is_shared, latitude, longitude, per_day, per_month, per_transaction, per_week, per_year, radius, remaining_limit, spending_limit, total, created_at, id, limit_set_at, updated_at, user_id, bank_account_number, card_color, card_icon, card_name, card_number, card_type, category_name, cvv, merchant_name) FROM stdin;
\.


--
-- Data for Name: chat_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_entity (id, user_id) FROM stdin;
\.


--
-- Data for Name: messages_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages_entity (chat_id, id, sender_id, sent_at, message_content) FROM stdin;
\.


--
-- Data for Name: notification_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notification_entity (read, created_at, id, user_id, body, title, data) FROM stdin;
\.


--
-- Data for Name: plan_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plan_entity (daily_spend_limit, has_category_locking, has_location_locking, has_merchant_locking, monthly_card_issuance_limit, monthly_spend_limit, price, id, name) FROM stdin;
500	f	f	t	10	5000	0	57	BASIC
2000	t	t	t	50	20000	5	58	PREMIUM
\.


--
-- Data for Name: shared_card_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shared_card_entity (card_id, expires_at, id, shared_at, user_id) FROM stdin;
\.


--
-- Data for Name: subscription_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscription_entity (amount, is_active, card_id, id, last_charge_date, next_charge_date, user_id, billing_cycle, category, merchant) FROM stdin;
\.


--
-- Data for Name: transaction_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction_entity (amount, is_recurring, latitude, longitude, card_id, created_at, id, user_id, category, decline_reason, description, merchant, status, type) FROM stdin;
\.


--
-- Data for Name: user_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_entity (auto_renewal, current_daily_spend, current_month_card_issuance, current_monthly_spend, daily_spend_limit, date_of_birth, is_active, monthly_card_issuance_limit, monthly_spend_limit, notification_enabled, created_at, id, last_spend_reset, plan_end_date, plan_start_date, bank_account_number, bank_account_username, civil_id, department, email, first_name, gender, last_name, notification_token, password, permission, phone_number, plan, profile_pic, role) FROM stdin;
f	0	0	0	500	1990-01-01	t	10	5000	t	2025-02-16 15:52:19.308467	52	2025-02-16 15:52:19.264867	\N	2025-02-16 15:52:19.264888	12234567890	johndoe	123456789133	\N	j@me.com	John	male	Doe	\N	$2a$10$snP2pqHLsSXmdKZNRKBf..czWQToiVHioiOMQevBg1v37ot8AaBVS	\N	+1234567890	BASIC	https://example.com/profile.jpg	ROLE_USER
\.


--
-- Name: card_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.card_entity_id_seq', 193, true);


--
-- Name: chat_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_entity_id_seq', 1, false);


--
-- Name: messages_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_entity_id_seq', 1, false);


--
-- Name: notification_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_entity_id_seq', 1561, true);


--
-- Name: plan_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plan_entity_id_seq', 66, true);


--
-- Name: shared_card_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shared_card_entity_id_seq', 1, false);


--
-- Name: subscription_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_entity_id_seq', 21, true);


--
-- Name: transaction_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_entity_id_seq', 1540, true);


--
-- Name: user_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_entity_id_seq', 52, true);


--
-- Name: card_entity card_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.card_entity
    ADD CONSTRAINT card_entity_pkey PRIMARY KEY (id);


--
-- Name: chat_entity chat_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_entity
    ADD CONSTRAINT chat_entity_pkey PRIMARY KEY (id);


--
-- Name: messages_entity messages_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages_entity
    ADD CONSTRAINT messages_entity_pkey PRIMARY KEY (id);


--
-- Name: notification_entity notification_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification_entity
    ADD CONSTRAINT notification_entity_pkey PRIMARY KEY (id);


--
-- Name: plan_entity plan_entity_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_entity
    ADD CONSTRAINT plan_entity_name_key UNIQUE (name);


--
-- Name: plan_entity plan_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_entity
    ADD CONSTRAINT plan_entity_pkey PRIMARY KEY (id);


--
-- Name: shared_card_entity shared_card_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shared_card_entity
    ADD CONSTRAINT shared_card_entity_pkey PRIMARY KEY (id);


--
-- Name: subscription_entity subscription_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_entity
    ADD CONSTRAINT subscription_entity_pkey PRIMARY KEY (id);


--
-- Name: transaction_entity transaction_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_entity
    ADD CONSTRAINT transaction_entity_pkey PRIMARY KEY (id);


--
-- Name: user_entity user_entity_bank_account_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_bank_account_number_key UNIQUE (bank_account_number);


--
-- Name: user_entity user_entity_civil_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_civil_id_key UNIQUE (civil_id);


--
-- Name: user_entity user_entity_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_email_key UNIQUE (email);


--
-- Name: user_entity user_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_pkey PRIMARY KEY (id);


--
-- Name: shared_card_entity fk1r1us2ovg06dd8b46bjfdfqdi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shared_card_entity
    ADD CONSTRAINT fk1r1us2ovg06dd8b46bjfdfqdi FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: card_entity fk5bkjlapt94djacsrc6o6bvghf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.card_entity
    ADD CONSTRAINT fk5bkjlapt94djacsrc6o6bvghf FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: chat_entity fk5m6pvsxl6h7jdy3yjg6f5lmp7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_entity
    ADD CONSTRAINT fk5m6pvsxl6h7jdy3yjg6f5lmp7 FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: transaction_entity fkbrpjvb8s92g0t6f8oh6oj895l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_entity
    ADD CONSTRAINT fkbrpjvb8s92g0t6f8oh6oj895l FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: transaction_entity fkcbtmbg9ya3gen9oas48xpyorf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_entity
    ADD CONSTRAINT fkcbtmbg9ya3gen9oas48xpyorf FOREIGN KEY (card_id) REFERENCES public.card_entity(id);


--
-- Name: subscription_entity fkckoo8jnsf7bkp8kceutmrg31h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_entity
    ADD CONSTRAINT fkckoo8jnsf7bkp8kceutmrg31h FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: shared_card_entity fkdfeord2t2he3w7sah2d2hvobg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shared_card_entity
    ADD CONSTRAINT fkdfeord2t2he3w7sah2d2hvobg FOREIGN KEY (card_id) REFERENCES public.card_entity(id);


--
-- Name: notification_entity fkgemicmmtfy225vqj5li4u96lk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification_entity
    ADD CONSTRAINT fkgemicmmtfy225vqj5li4u96lk FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: subscription_entity fkk1ejdboh4h1j6nl7t4w6b43gk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_entity
    ADD CONSTRAINT fkk1ejdboh4h1j6nl7t4w6b43gk FOREIGN KEY (card_id) REFERENCES public.card_entity(id);


--
-- Name: messages_entity fkmnytxskq3hr37hd0ytkdk6si8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages_entity
    ADD CONSTRAINT fkmnytxskq3hr37hd0ytkdk6si8 FOREIGN KEY (chat_id) REFERENCES public.chat_entity(id);


--
-- PostgreSQL database dump complete
--

